### ISSUE TITLE
Docs: add instructions to run the app locally.

### ISSUE THREAD

**Issue by HenriqueMartinsBotelho** [JammUtkarsh/gfstat#4]
# Issue: Add Running Instructions to Readme.md

## Description

The purpose of this issue is to include clear and detailed instructions on how to run the application in the Readme.md file. These instructions should be easy to follow and should cover all necessary steps to install and run the application in a local environment.

**Comment by jammutkarsh** [comment]
Yes that is a long overdue task. I'll try to add that this by this weekend.

But for now you can run the app using
```bash
export $(cat .env | xargs) # to set env vars from .env
go run . # you are up and running.
```
in `.env` file you need
```env
GH_BASIC_CLIENT_ID=1234abc
GH_BASIC_SECRET_ID=1234xyz
```
These two values which you get from [New OAuth App](https://github.com/settings/developers).
